sudo: required
language: node_js
node_js:
  - 0.10
before_install:
  - Xvfb :99 -screen scrn 1024x768x8 &
  - "[[ -f selenium-server-standalone-2.46.0.jar ]] || wget http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar"
  - java -jar selenium-server-standalone-2.46.0.jar &
script:
  - export DISPLAY=":99" && SELENIUM_BROWSER=firefox HUB_PORT=4444 CUCUMBER_TAGS=~@CI_exclude meteor run --test 2>&1
  - cat $WORKSPACE/build/ecohealthalliance/rana/.meteor/local/log/cucumber.log
